int32 mode_lf_1
float32 t_lf_1
float32 w_lf_1
float32 pos_lf_1
float32 k_p_lf_1
float32 k_w_lf_1

int32 mode_lf_2
float32 t_lf_2
float32 w_lf_2
float32 pos_lf_2
float32 k_p_lf_2
float32 k_w_lf_2

int32 mode_lf_3
float32 t_lf_3
float32 w_lf_3
float32 pos_lf_3
float32 k_p_lf_3
float32 k_w_lf_3

int32 mode_rf_1
float32 t_rf_1
float32 w_rf_1
float32 pos_rf_1
float32 k_p_rf_1
float32 k_w_rf_1

int32 mode_rf_2
float32 t_rf_2
float32 w_rf_2
float32 pos_rf_2
float32 k_p_rf_2
float32 k_w_rf_2

int32 mode_rf_3
float32 t_rf_3
float32 w_rf_3
float32 pos_rf_3
float32 k_p_rf_3
float32 k_w_rf_3

int32 mode_lb_1
float32 t_lb_1
float32 w_lb_1
float32 pos_lb_1
float32 k_p_lb_1
float32 k_w_lb_1

int32 mode_lb_2
float32 t_lb_2
float32 w_lb_2
float32 pos_lb_2
float32 k_p_lb_2
float32 k_w_lb_2

int32 mode_lb_3
float32 t_lb_3
float32 w_lb_3
float32 pos_lb_3
float32 k_p_lb_3
float32 k_w_lb_3

int32 mode_rb_1
float32 t_rb_1
float32 w_rb_1
float32 pos_rb_1
float32 k_p_rb_1
float32 k_w_rb_1

int32 mode_rb_2
float32 t_rb_2
float32 w_rb_2
float32 pos_rb_2
float32 k_p_rb_2
float32 k_w_rb_2

int32 mode_rb_3
float32 t_rb_3
float32 w_rb_3
float32 pos_rb_3
float32 k_p_rb_3
float32 k_w_rb_3
